export const body = document.getElementById('body');
export const container = document.createElement('div');
export const header = document.createElement('div');
export const headerTitle = document.createElement('div');
export const main = document.createElement('main');
export const mainInner = document.createElement('div');
export const buttonsField = document.createElement('div');
export const easyButton = document.createElement('button');
export const normalButton = document.createElement('button');
export const hardButton = document.createElement('button');
export const mode = document.createElement('div');
export const modeName = document.createElement('div');
export const modeDesc = document.createElement('div');
export const gamefield = document.createElement('div');
export const newGameButton = document.createElement('button');
export const cells = document.getElementsByClassName('cell');
export const gameInformation = document.createElement('div')
export const timer = document.createElement('div');
export const minutes = document.createElement('div');
export const seconds = document.createElement('div');
export const milliseconds = document.createElement('div');
export const minesCount = document.createElement('div');
export const flagsCount = document.createElement('div');
export const clicksCount = document.createElement('div');

container.classList.add('container');
header.classList.add('header');
headerTitle.classList.add('header__title');
main.classList.add('main');
mainInner.classList.add('main__inner');
mode.classList.add('mode');
modeName.classList.add('mode__name');
modeDesc.classList.add('mode__desc');
buttonsField.classList.add('main__buttons')
easyButton.classList.add('button');
easyButton.innerHTML = 'Easy';
normalButton.classList.add('button');
normalButton.innerHTML = 'Normal';
hardButton.classList.add('button');
hardButton.innerHTML = 'Hard';
gamefield.classList.add('game');
newGameButton.classList.add('button');
newGameButton.innerHTML = 'New Game';
gameInformation.classList.add('mode__information');
timer.classList.add('timer');
minutes.classList.add('minutes');
seconds.classList.add('seconds');
milliseconds.classList.add('milliseconds');
